### PR TITLE
Updated ControlFlow with Pause documentation.

### PR DESCRIPTION
**Pull request by NonstickAtom785**
Could you please add a note explaining what the Pause If with funcpointer does?

### CODE REVIEW

**Comment by Zeda** [comment]
Oof, we have conflicting files; this ought to be fun :P

**Comment by NonstickAtom785** [comment]
No it's fixed!

**Review by NonstickAtom785 — COMMENTED** [review]
I was trying to find a way to make an explanation for the func pointer things. Thanks for helping!

**Comment by Zeda** [comment]
Awesome, thanks! Now on to merging and breaking this thing.

**Pull request merged**
